CREATE SCHEMA IF NOT EXISTS city_mgmt;
CREATE TABLE IF NOT EXISTS city_mgmt.requests
(
    id SERIAL PRIMARY KEY,
    app VARCHAR(15),
    request VARCHAR(1000),
    response VARCHAR(1000)
);
INSERT INTO city_mgmt.requests (id, app, request, response) VALUES (1, 'user_mgmt', '{"name":"Jon Doe","email":"Jon_Doe@Gmail.com","phone":"1122334455","role":"city_planner","password":"123"}', '{"userId":1,"name":"Jon Doe","email":"Jon_Doe@Gmail.com","phone":"1122334455","password":"$2b$10$XUXHk414IT/Rd2/uJkXbiejTDPFc4iAbiXn/MlwOtz79luXhUJKIe","role":"city_planner"}');
INSERT INTO city_mgmt.requests (id, app, request, response) VALUES (2, 'user_mgmt', '{"name":"Jon Rose","email":"jon_rose@test.com","phone":"1234567798","role":"citizen","password":"123"}', '{"userId":2,"name":"Jon Rose","email":"jon_rose@test.com","phone":"1234567798","password":"$2b$10$D3T0O0EQiQCcTgpRDOU4V.AaMhqrcaBp28N5HWSgr8i16Ji1mboBq","role":"citizen"}');
INSERT INTO city_mgmt.requests (id, app, request, response) VALUES (3, 'user_mgmt', '{"name":"Jeffar","email":"jeffar21@test.com","phone":"1234512345","role":"city_planner","password":"123"}', '{"userId":3,"name":"Jeffar","email":"jeffar21@test.com","phone":"1234512345","password":"$2b$10$AUjJxx.um0C52udiLLDtmOm0l7i4L5uKS0y6up7I7W29E7g/ww5T.","role":"city_planner"}');
INSERT INTO city_mgmt.requests (id, app, request, response) VALUES (4, 'user_mgmt', '{"name":"Jonson","email":"jonson@test.com","phone":"1223344515","role":"citizen","password":"123"}', '{"userId":4,"name":"Jonson","email":"jonson@test.com","phone":"1223344515","password":"$2b$10$.2udKLg5ccvQ91iMEkESpeDgzMAmqFToD0LSOVwKqb7L49r0u/ixW","role":"citizen"}');
INSERT INTO city_mgmt.requests (id, app, request, response) VALUES (5, 'user_mgmt', '{"name":"Rahul Kumar","email":"rahul_new@test.com","phone":"2233445566","role":"citizen","password":"123"}', '{"userId":5,"name":"Rahul Kumar","email":"rahul_new@test.com","phone":"2233445566","password":"$2b$10$0Ow2T6WfAUnLWPgA9JbwtuSK25bnUodXfvXw6A5bt4iym8p9R7Ily","role":"citizen"}');
INSERT INTO city_mgmt.requests (id, app, request, response) VALUES (6, 'user_mgmt', '{"name":"Bhanu Pratap Das","email":"bhanu@test.com","phone":"12345654321","role":"city_planner","password":"123"}', '{"userId":6,"name":"Bhanu Pratap Das","email":"bhanu@test.com","phone":"12345654321","password":"$2b$10$1TExJ7OiGcuRRePnIJBB9ulSowmeGkyrtJJH2J..c2tL.u.URTtVC","role":"city_planner"}');
INSERT INTO city_mgmt.requests (id, app, request, response) VALUES (7, 'user_mgmt', '{"email":"Jon_Doe@Gmail.com","password":"123"}', '{"access_token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxIiwiZW1haWwiOiJKb25fRG9lQEdtYWlsLmNvbSIsInJvbGUiOiJjaXR5X3BsYW5uZXIiLCJpYXQiOjE3NDk2MzI5OTUsImV4cCI6MTc0OTYzMzg5NX0.D3YWIfXVF9TBgFZ7ydIGXxpMwRYmRa56rCxhE4wajvA","user":{"userId":1,"name":"Jon Doe","email":"Jon_Doe@Gmail.com","phone":"1122334455","role":"city_planner"}}');
INSERT INTO city_mgmt.requests (id, app, request, response) VALUES (8, 'energy_mgmt', '{"city":"Dortmund","address":"ErmlingStr 1","zipCode":44222,"ownerEmail":"rahul_new@test.com","floorArea":26,"energyType":"electricity","startDate":"2024-03-01","endDate":"2024-05-31","consumption":458}', '{"city":"Dortmund","address":"ErmlingStr 1","zipCode":44222,"ownerEmail":"rahul_new@test.com","floorArea":26,"energyType":"electricity","startDate":"2024-03-01","endDate":"2024-05-31","consumption":458,"status":"Building and Energy Source registered successfully."}');
INSERT INTO city_mgmt.requests (id, app, request, response) VALUES (9, 'energy_mgmt', '{"city":"Dortmund","address":"ErmlingStr 23","zipCode":44225,"ownerEmail":"jonson@test.com","floorArea":32,"energyType":"gas","startDate":"2024-04-01","endDate":"2024-07-31","consumption":628}', '{"city":"Dortmund","address":"ErmlingStr 23","zipCode":44225,"ownerEmail":"jonson@test.com","floorArea":32,"energyType":"gas","startDate":"2024-04-01","endDate":"2024-07-31","consumption":628,"status":"Building and Energy Source registered successfully."}');
INSERT INTO city_mgmt.requests (id, app, request, response) VALUES (10, 'energy_anlyt', '"rahul_new@test.com 2024-01-01"', '[{"address":"ErmlingStr 1","consumption":458,"energyType":"electricity","unit":"kwh","city":"Dortmund","zipcode":44222,"provider":"RWE"}]');
INSERT INTO city_mgmt.requests (id, app, request, response) VALUES (11, 'energy_mgmt', '{"city":"Dortmund","address":"Stiftstr 2","zipCode":44323,"ownerEmail":"jon_rose@test.com","floorArea":45,"energyType":"heating-pump","startDate":"2024-02-01","endDate":"2024-05-31","consumption":532}', '{"city":"Dortmund","address":"Stiftstr 2","zipCode":44323,"ownerEmail":"jon_rose@test.com","floorArea":45,"energyType":"heating-pump","startDate":"2024-02-01","endDate":"2024-05-31","consumption":532,"status":"Building and Energy Source registered successfully."}');
INSERT INTO city_mgmt.requests (id, app, request, response) VALUES (12, 'user_mgmt', '{"email":"jon_rose@test.com","password":"123"}', '{"access_token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIyIiwiZW1haWwiOiJqb25fcm9zZUB0ZXN0LmNvbSIsInJvbGUiOiJjaXRpemVuIiwiaWF0IjoxNzQ5NjMzNTE4LCJleHAiOjE3NDk2MzQ0MTh9.7pJ-wprEe783vV3Xhjn8veLZiNHRe9Ux1hS74yhf8V4","user":{"userId":2,"name":"Jon Rose","email":"jon_rose@test.com","phone":"1234567798","role":"citizen"}}');
INSERT INTO city_mgmt.requests (id, app, request, response) VALUES (13, 'energy_anlyt', '"jon_rose@test.com 2024-01-01"', '[{"address":"Stiftstr 2","consumption":532,"energyType":"heating-pump","unit":"m3","city":"Dortmund","zipcode":44323,"provider":"octapus"}]');
INSERT INTO city_mgmt.requests (id, app, request, response) VALUES (14, 'energy_anlyt', '"Dortmund 2024-01-01"', '[{"address":"ErmlingStr 23","consumption":628,"energyType":"gas","unit":"m3","city":"Dortmund","zipcode":44225,"provider":"DEW21"},{"address":"Stiftstr 2","consumption":532,"energyType":"heating-pump","unit":"m3","city":"Dortmund","zipcode":44323,"provider":"octapus"},{"address":"ErmlingStr 1","consumption":458,"energyType":"electricity","unit":"kwh","city":"Dortmund","zipcode":44222,"provider":"RWE"}]');
INSERT INTO city_mgmt.requests (id, app, request, response) VALUES (15, 'energy_opt', '"jon_rose@test.com"', '"🏠 Building at Stiftstr 2\n  🔌 Energy type: heating-pump, cost: ���313.88\n  💡 Tip: Consider switching to solar (price: €0.35/unit).\n  ✅ Good job! Your energy usage is efficient at 32 kWh/m²/year.\n  🌱 Switching to Solar or Heat Pump can save you money in the long run while helping the planet. It''s a smart, sustainable choice! 🌍\n\n"');
INSERT INTO city_mgmt.requests (id, app, request, response) VALUES (16, 'energy_mgmt', '{"ownerEmail":"jon_rose@test.com","energyType":"electricity","startDate":"2024-06-01","endDate":"2024-08-30","consumption":357}', '{"ownerEmail":"jon_rose@test.com","energyType":"electricity","startDate":"2024-06-01","endDate":"2024-08-30","consumption":357,"status":"Energy Source added successfully."}');
INSERT INTO city_mgmt.requests (id, app, request, response) VALUES (17, 'energy_mgmt', '{"ownerEmail":"rahul_new@test.com","energyType":"electricity","startDate":"2024-09-01","endDate":"2024-11-30","consumption":411}', '{"ownerEmail":"rahul_new@test.com","energyType":"electricity","startDate":"2024-09-01","endDate":"2024-11-30","consumption":411,"status":"Energy Source added successfully."}');
INSERT INTO city_mgmt.requests (id, app, request, response) VALUES (18, 'energy_mgmt', '{"ownerEmail":"jon_rose@test.com","energyType":"electricity","startDate":"2024-09-01","endDate":"2024-11-30","consumption":413}', '{"ownerEmail":"jon_rose@test.com","energyType":"electricity","startDate":"2024-09-01","endDate":"2024-11-30","consumption":413,"status":"Energy Source updated successfully."}');
INSERT INTO city_mgmt.requests (id, app, request, response) VALUES (19, 'energy_anlyt', '"Dortmund 2024-01-01"', '[{"address":"ErmlingStr 23","consumption":628,"energyType":"gas","unit":"m3","city":"Dortmund","zipcode":44225,"provider":"DEW21"},{"address":"Stiftstr 2","consumption":532,"energyType":"heating-pump","unit":"m3","city":"Dortmund","zipcode":44323,"provider":"octapus"},{"address":"ErmlingStr 1","consumption":458,"energyType":"electricity","unit":"kwh","city":"Dortmund","zipcode":44222,"provider":"RWE"},{"address":"Stiftstr 2","consumption":413,"energyType":"electricity","unit":"kwh","city":"Dortmund","zipcode":44323,"provider":"RWE"},{"address":"ErmlingStr 1","consumption":411,"energyType":"electricity","unit":"kwh","city":"Dortmund","zipcode":44222,"provider":"RWE"}]');
INSERT INTO city_mgmt.requests (id, app, request, response) VALUES (20, 'user_mgmt', '{"email":"Jon_Doe@Gmail.com","password":"123"}', '{"access_token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxIiwiZW1haWwiOiJKb25fRG9lQEdtYWlsLmNvbSIsInJvbGUiOiJjaXR5X3BsYW5uZXIiLCJpYXQiOjE3NDk2MzQyNjcsImV4cCI6MTc0OTYzNTE2N30.8Z2AHyD2QDPgrj_tCQxvjxTt2uwxV4IB8Z4Kug8SUTk","user":{"userId":1,"name":"Jon Doe","email":"Jon_Doe@Gmail.com","phone":"1122334455","role":"city_planner"}}');
INSERT INTO city_mgmt.requests (id, app, request, response) VALUES (21, 'user_mgmt', '{"email":"rahul_new@test.com","password":"123"}', '{"access_token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1IiwiZW1haWwiOiJyYWh1bF9uZXdAdGVzdC5jb20iLCJyb2xlIjoiY2l0aXplbiIsImlhdCI6MTc0OTYzNDI3OCwiZXhwIjoxNzQ5NjM1MTc4fQ.96VDpls1Aq5BUp1mr-TTAJ_PVLQ5esXX-pKyji82nKg","user":{"userId":5,"name":"Rahul Kumar","email":"rahul_new@test.com","phone":"2233445566","role":"citizen"}}');
INSERT INTO city_mgmt.requests (id, app, request, response) VALUES (22, 'energy_opt', '"rahul_new@test.com"', '"🏠 Building at ErmlingStr 1\n  🔌 Energy type: electricity, cost: €184.95\n  💡 Tip: Consider switching to solar (price: €0.35/unit).\n  ✅ Good job! Your energy usage is efficient at 56 kWh/m²/year.\n  🌱 Switching to Solar or Heat Pump can save you money in the long run while helping the planet. It''s a smart, sustainable choice! 🌍\n\n"');
INSERT INTO city_mgmt.requests (id, app, request, response) VALUES (23, 'energy_anlyt', '"rahul_new@test.com 2024-04-11"', '[{"address":"ErmlingStr 1","consumption":411,"energyType":"electricity","unit":"kwh","city":"Dortmund","zipcode":44222,"provider":"RWE"}]');
INSERT INTO city_mgmt.requests (id, app, request, response) VALUES (24, 'energy_anlyt', '"rahul_new@test.com 2024-01-01"', '[{"address":"ErmlingStr 1","consumption":458,"energyType":"electricity","unit":"kwh","city":"Dortmund","zipcode":44222,"provider":"RWE"},{"address":"ErmlingStr 1","consumption":411,"energyType":"electricity","unit":"kwh","city":"Dortmund","zipcode":44222,"provider":"RWE"}]');
INSERT INTO city_mgmt.requests (id, app, request, response) VALUES (25, 'energy_anlyt', '"44222 2024-01-01"', '[{"address":"ErmlingStr 1","consumption":458,"energyType":"electricity","unit":"kwh","city":"Dortmund","zipcode":44222,"provider":"RWE"},{"address":"ErmlingStr 1","consumption":411,"energyType":"electricity","unit":"kwh","city":"Dortmund","zipcode":44222,"provider":"RWE"}]');
INSERT INTO city_mgmt.requests (id, app, request, response) VALUES (26, 'energy_opt', '"rahul_new@test.com"', '"🏠 Building at ErmlingStr 1\n  🔌 Energy type: electricity, cost: €184.95\n  💡 Tip: Consider switching to solar (price: €0.35/unit).\n  ✅ Good job! Your energy usage is efficient at 56 kWh/m²/year.\n  🌱 Switching to Solar or Heat Pump can save you money in the long run while helping the planet. It''s a smart, sustainable choice! 🌍\n\n"');
INSERT INTO city_mgmt.requests (id, app, request, response) VALUES (27, 'user_mgmt', '{"email":"rahul_new@test.com","password":"123"}', '{"access_token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1IiwiZW1haWwiOiJyYWh1bF9uZXdAdGVzdC5jb20iLCJyb2xlIjoiY2l0aXplbiIsImlhdCI6MTc0OTYzNDgzNSwiZXhwIjoxNzQ5NjM1NzM1fQ.5sui8lv1luGFQo4Z_NGhkXbWi_IAuE1sXbmkj6VPKB4","user":{"userId":5,"name":"Rahul Kumar","email":"rahul_new@test.com","phone":"2233445566","role":"citizen"}}');
INSERT INTO city_mgmt.requests (id, app, request, response) VALUES (28, 'user_mgmt', '{"email":"rahul_new@test.com","password":"123"}', '{"access_token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1IiwiZW1haWwiOiJyYWh1bF9uZXdAdGVzdC5jb20iLCJyb2xlIjoiY2l0aXplbiIsImlhdCI6MTc0OTYzNTI1NiwiZXhwIjoxNzQ5NjM2MTU2fQ.Fq3eTORu58gLUcCqHvQquTr3s6zHeL68K_fXgUtsYsc","user":{"userId":5,"name":"Rahul Kumar","email":"rahul_new@test.com","phone":"2233445566","role":"citizen"}}');
INSERT INTO city_mgmt.requests (id, app, request, response) VALUES (29, 'user_mgmt', '{"email":"jonson@test.com","password":"123"}', '{"access_token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI0IiwiZW1haWwiOiJqb25zb25AdGVzdC5jb20iLCJyb2xlIjoiY2l0aXplbiIsImlhdCI6MTc0OTYzNTM3NiwiZXhwIjoxNzQ5NjM2Mjc2fQ.3q_neticVmA3aWa0UGYSntsYhf1f0-crULfrCB1xZHw","user":{"userId":4,"name":"Jonson","email":"jonson@test.com","phone":"1223344515","role":"citizen"}}');
INSERT INTO city_mgmt.requests (id, app, request, response) VALUES (30, 'energy_mgmt', '{"ownerEmail":"jonson@test.com","energyType":"heating-pump","startDate":"2024-08-01","endDate":"2024-11-30","consumption":444}', '{"ownerEmail":"jonson@test.com","energyType":"heating-pump","startDate":"2024-08-01","endDate":"2024-11-30","consumption":444,"status":"Energy Source added successfully."}');
INSERT INTO city_mgmt.requests (id, app, request, response) VALUES (31, 'energy_mgmt', '{"ownerEmail":"jonson@test.com","energyType":"gas","startDate":"2024-08-01","endDate":"2024-12-31","consumption":437}', '{"ownerEmail":"jonson@test.com","energyType":"gas","startDate":"2024-08-01","endDate":"2024-12-31","consumption":437,"status":"Energy Source updated successfully."}');
INSERT INTO city_mgmt.requests (id, app, request, response) VALUES (32, 'energy_mgmt', '{"ownerEmail":"jonson@test.com","energyType":"solar","startDate":"2025-01-01","endDate":"2025-03-31","consumption":333}', '{"ownerEmail":"jonson@test.com","energyType":"solar","startDate":"2025-01-01","endDate":"2025-03-31","consumption":333,"status":"Energy Source added successfully."}');
INSERT INTO city_mgmt.requests (id, app, request, response) VALUES (33, 'energy_mgmt', '{"ownerEmail":"jonson@test.com","energyType":"solar","startDate":"2025-01-01","endDate":"2025-04-30","consumption":335}', '{"ownerEmail":"jonson@test.com","energyType":"solar","startDate":"2025-01-01","endDate":"2025-04-30","consumption":335,"status":"Energy Source updated successfully."}');
INSERT INTO city_mgmt.requests (id, app, request, response) VALUES (34, 'energy_opt', '"jonson@test.com"', '"🏠 Building at ErmlingStr 23\n  🔌 Energy type: solar, cost: €117.25\n  ✅ Good job! Your energy usage is efficient at 23 kWh/m²/year.\n\n"');
INSERT INTO city_mgmt.requests (id, app, request, response) VALUES (35, 'energy_anlyt', '"Dortmund 2024-01-01"', '[{"address":"Stiftstr 2","consumption":532,"energyType":"heating-pump","unit":"m3","city":"Dortmund","zipcode":44323,"provider":"octapus"},{"address":"ErmlingStr 1","consumption":458,"energyType":"electricity","unit":"kwh","city":"Dortmund","zipcode":44222,"provider":"RWE"},{"address":"ErmlingStr 23","consumption":444,"energyType":"heating-pump","unit":"m3","city":"Dortmund","zipcode":44225,"provider":"octapus"},{"address":"ErmlingStr 23","consumption":437,"energyType":"gas","unit":"m3","city":"Dortmund","zipcode":44225,"provider":"DEW21"},{"address":"Stiftstr 2","consumption":413,"energyType":"electricity","unit":"kwh","city":"Dortmund","zipcode":44323,"provider":"RWE"},{"address":"ErmlingStr 1","consumption":411,"energyType":"electricity","unit":"kwh","city":"Dortmund","zipcode":44222,"provider":"RWE"},{"address":"ErmlingStr 23","consumption":335,"energyType":"solar","unit":"m3","city":"Dortmund","zipcode":44225,"provider":"E-ON"}]');
INSERT INTO city_mgmt.requests (id, app, request, response) VALUES (36, 'energy_anlyt', '"44225 2024-01-01"', '[{"address":"ErmlingStr 23","consumption":444,"energyType":"heating-pump","unit":"m3","city":"Dortmund","zipcode":44225,"provider":"octapus"},{"address":"ErmlingStr 23","consumption":437,"energyType":"gas","unit":"m3","city":"Dortmund","zipcode":44225,"provider":"DEW21"},{"address":"ErmlingStr 23","consumption":335,"energyType":"solar","unit":"m3","city":"Dortmund","zipcode":44225,"provider":"E-ON"}]');
INSERT INTO city_mgmt.requests (id, app, request, response) VALUES (37, 'user_mgmt', '{"email":"jonson@test.com","password":"123"}', '{"access_token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI0IiwiZW1haWwiOiJqb25zb25AdGVzdC5jb20iLCJyb2xlIjoiY2l0aXplbiIsImlhdCI6MTc0OTYzNTk3NCwiZXhwIjoxNzQ5NjM2ODc0fQ.4HCKsCRbNIou56IV7uJejZJwkLexjNHErxKyxYMovcE","user":{"userId":4,"name":"Jonson","email":"jonson@test.com","phone":"1223344515","role":"citizen"}}');
INSERT INTO city_mgmt.requests (id, app, request, response) VALUES (38, 'energy_anlyt', '"jonson@test.com 2025-01-01"', '[{"address":"ErmlingStr 23","consumption":335,"energyType":"solar","unit":"m3","city":"Dortmund","zipcode":44225,"provider":"E-ON"}]');
INSERT INTO city_mgmt.requests (id, app, request, response) VALUES (39, 'energy_anlyt', '"jonson@test.com 2025-05-01"', '[]');
INSERT INTO city_mgmt.requests (id, app, request, response) VALUES (40, 'user_mgmt', '{"email":"jonson@test.com","password":"123"}', '{"access_token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI0IiwiZW1haWwiOiJqb25zb25AdGVzdC5jb20iLCJyb2xlIjoiY2l0aXplbiIsImlhdCI6MTc0OTYzNjAyMiwiZXhwIjoxNzQ5NjM2OTIyfQ.bI-NuXIVInonfVr08OKiF2YzxHDBluczSJk3Su8HW6c","user":{"userId":4,"name":"Jonson","email":"jonson@test.com","phone":"1223344515","role":"citizen"}}');
INSERT INTO city_mgmt.requests (id, app, request, response) VALUES (41, 'energy_anlyt', '"Dortmund 2025-03-01"', '[]');
INSERT INTO city_mgmt.requests (id, app, request, response) VALUES (42, 'user_mgmt', '{"email":"jonson@test.com","password":"123"}', '{"access_token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI0IiwiZW1haWwiOiJqb25zb25AdGVzdC5jb20iLCJyb2xlIjoiY2l0aXplbiIsImlhdCI6MTc0OTYzNjA4MiwiZXhwIjoxNzQ5NjM2OTgyfQ.66ZJ3P5QmLFnO_m7ypbAwhxGITKK7T8x4Y7XXO3iKuk","user":{"userId":4,"name":"Jonson","email":"jonson@test.com","phone":"1223344515","role":"citizen"}}');
INSERT INTO city_mgmt.requests (id, app, request, response) VALUES (43, 'energy_anlyt', '"Dortmund 2025-03-01"', '[]');
INSERT INTO city_mgmt.requests (id, app, request, response) VALUES (44, 'user_mgmt', '{"email":"jonson@test.com","password":"123"}', '{"access_token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI0IiwiZW1haWwiOiJqb25zb25AdGVzdC5jb20iLCJyb2xlIjoiY2l0aXplbiIsImlhdCI6MTc0OTYzNjIwMiwiZXhwIjoxNzQ5NjM3MTAyfQ.EChsuxScxNwjdzawqizU6anQmtqz10hUhgZhX_gv9CI","user":{"userId":4,"name":"Jonson","email":"jonson@test.com","phone":"1223344515","role":"citizen"}}');
INSERT INTO city_mgmt.requests (id, app, request, response) VALUES (45, 'energy_anlyt', '"Dortmund 2024-03-01"', '[{"address":"ErmlingStr 1","consumption":458,"energyType":"electricity","unit":"kwh","city":"Dortmund","zipcode":44222,"provider":"RWE"},{"address":"ErmlingStr 23","consumption":444,"energyType":"heating-pump","unit":"m3","city":"Dortmund","zipcode":44225,"provider":"octapus"},{"address":"ErmlingStr 23","consumption":437,"energyType":"gas","unit":"m3","city":"Dortmund","zipcode":44225,"provider":"DEW21"},{"address":"Stiftstr 2","consumption":413,"energyType":"electricity","unit":"kwh","city":"Dortmund","zipcode":44323,"provider":"RWE"},{"address":"ErmlingStr 1","consumption":411,"energyType":"electricity","unit":"kwh","city":"Dortmund","zipcode":44222,"provider":"RWE"},{"address":"ErmlingStr 23","consumption":335,"energyType":"solar","unit":"m3","city":"Dortmund","zipcode":44225,"provider":"E-ON"}]');
INSERT INTO city_mgmt.requests (id, app, request, response) VALUES (46, 'energy_opt', '"jonson@test.com"', '"🏠 Building at ErmlingStr 23\n  🔌 Energy type: solar, cost: €117.25\n  ✅ Good job! Your energy usage is efficient at 23 kWh/m²/year.\n\n"');
COMMIT;
