services:
  db:
    image: postgres:17.5
    container_name: db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
  eureka_server:
    image: bhanupdas/eureka_server:latest
    container_name: eureka_server
    ports:
      - "8761:8761"
  user_management_service:
    image: bhanupdas/user_management_service:latest
    container_name: user_management_service
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=admin
      - DB_PASSWORD=password
      - DB_SCHEMA=user_mgmt
      - DB_NAME=postgres
      - JWT_SECRET=JWT_SECRET
      - JWT_EXPIRATION=900
      - HTTP_PORT=4000
      - TCP_PORT=8001
      - SERVICE_NAME=user_management
      - SERVICE_PORT=4000
      - SERVICE_HOST=localhost
      - SERVICE_ipAddr=127.0.0.1
      - EUREKA_SERVER_HOST=eureka_server
      - EUREKA_SERVER_PORT=8761
      - LOKI_URL=http://loki:3100/
    ports:
      - '4000:4000'
    depends_on:
      - db
      - eureka_server
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
  loki:
    image: grafana/loki
    ports:
      - '3100:3100'
    command: -config.file=/etc/loki/local-config.yaml
volumes:
  pgdata:
  node_modules: