services:
  db:
    image: postgres:17.5
    container_name: db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
  eureka_server:
    image: bhanupdas/eureka_server:latest
    container_name: eureka_server
    ports:
      - '8761:8761'
  loki:
    image: grafana/loki
    ports:
      - '3100:3100'
    command: -config.file=/etc/loki/local-config.yaml
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
  grafana:
    image: grafana/grafana-enterprise:latest
    container_name: grafana
    ports:
      - '3000:3000'
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
      - loki
  usermgmt:
    image: bhanupdas/user-management-service:latest
    container_name: usermgmt
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=admin
      - DB_PASSWORD=password
      - DB_SCHEMA=user_mgmt
      - DB_NAME=postgres
      - JWT_SECRET=JWT_SECRET
      - JWT_EXPIRATION=900
      - HTTP_PORT=4000
      - TCP_PORT=8001
      - SERVICE_NAME=usermgmt
      - SERVICE_PORT=4000
      - SERVICE_HOST=localhost
      - SERVICE_ipAddr=127.0.0.1
      - EUREKA_SERVER_HOST=eureka_server
      - EUREKA_SERVER_PORT=8761
      - LOKI_URL=http://loki:3100/
    ports:
      - '4000:4000'
    depends_on:
      - db
      - eureka_server
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
volumes:
  pgdata: null
  node_modules: null
