apiVersion: 1

datasources:
  - name: "Prometheus-1"
    type: prometheus
    url: http://host.docker.internal:9090
    access: proxy
    isDefault: true
    jsonData:
      httpMethod: "POST"
  - name: "Loki"
    type: loki
    url: http://loki:3100
    access: proxy
    isDefault: false
    jsonData: {}