services:
  auth:
    build: 
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: npm run start:dev auth
    env_file:
      - ./.env
    environment:
      - DB_HOST=db
      - DB_PORT=5432
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
  db:
    image: postgres:14.1-alpine
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '5433:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    
volumes:
  pgdata: