global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'nestjs-app'
    metrics_path: /metrics
    static_configs:
      - targets:
          # - host.docker.internal:4000
          - auth:4000
